### PR TITLE
fix: releases missing when run the 'list -A' command

### PR DESCRIPTION
**Pull request by shipengqi**
**What this PR does / why we need it**:

fix: release missing when run the 'list -A' command

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by ralfv — APPROVED** [review]

**Comment by ralfv** [comment]
So the signoff message in your commits is not necessary here?

**Comment by shipengqi** [comment]
> So the signoff message in your commits is not necessary here?

I updated the commit messages and the signoff message is added

**Comment by shipengqi** [comment]
This PR just fixes the 'list -A' command issue, I'll create another PR to add unit tests.

**Comment by shipengqi** [comment]
Hi @ralfv, @yong-jie-gong I have already added unit tests for the multisecrets, please help to review.

**Comment by ralfv** [comment]
> Hi @ralfv, @yong-jie-gong I have already added unit tests for the multisecrets, please help to review.

I think we'll want to create MultiReleaseStub() in mock_test.go and provide some more data points like .Manifest to have a) more data in a release secret and b) test the splitting. We don't need much data, I think a JSON document and a chunk size of like 80 characters should be enough for testing.

The test can consist of recreating the original input JSON, checking the number of chunks created, checking the secret naming.

**Comment by shipengqi** [comment]
> > Hi @ralfv, @yong-jie-gong I have already added unit tests for the multisecrets, please help to review.
> 
> I think we'll want to create MultiReleaseStub() in mock_test.go and provide some more data points like .Manifest to have a) more data in a release secret and b) test the splitting. We don't need much data, I think a JSON document and a chunk size of like 80 characters should be enough for testing.
> 
> The test can consist of recreating the original input JSON, checking the number of chunks created, checking the secret naming.

Done, please help to review.

**Pull request merged**
